from distutils.core import setup

setup(name="iclrt_tools",
    version="1.0",
    description="Tools used for data analysis at the ICLRT",
    author="Jaime A. Caicedo",
    author_email="jaime.caicedo@ufl.edu",
    packages = ['iclrt_tools',
                'iclrt_tools.antenna_decay',
                'iclrt_tools.cameras',
                'iclrt_tools.data_sets',
                'iclrt_tools.differentiators',
                'iclrt_tools.field_mill',
                'iclrt_tools.filters',
                'iclrt_tools.fourier_analysis',
                'iclrt_tools.integrators',
                'iclrt_tools.irig',
                'iclrt_tools.lat_lon',
                'iclrt_tools.lma',
                'iclrt_tools.lma.analysis',
                'iclrt_tools.models',
                'iclrt_tools.models.current_fit',
                'iclrt_tools.models.current_waves',
                'iclrt_tools.models.wave_model',
                'iclrt_tools.nldn',
                'iclrt_tools.oscilloscopes',
                'iclrt_tools.plotting',
                'iclrt_tools.timing',
                ]
    )